--
-- Type: TABLE; Owner: SEARCHAPP; Name: BK_BIO_ANALYSIS_ATTRIBUTE_LIN
--
 CREATE TABLE "SEARCHAPP"."BK_BIO_ANALYSIS_ATTRIBUTE_LIN" 
  (	"BIO_ANALYSIS_ATT_LINEAGE_ID" NUMBER NOT NULL ENABLE, 
"BIO_ANALYSIS_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
"ANCESTOR_TERM_ID" NUMBER NOT NULL ENABLE, 
"ANCESTOR_SEARCH_KEYWORD_ID" NUMBER NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
