--
-- Type: SEQUENCE; Owner: SEARCHAPP; Name: SEQ_SAVED_FACETED_SEARCH_ID
--
CREATE SEQUENCE  "SEARCHAPP"."SEQ_SAVED_FACETED_SEARCH_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 318 CACHE 20 NOORDER  NOCYCLE ;

--
-- Type: TABLE; Owner: SEARCHAPP; Name: SAVED_FACETED_SEARCH
--
 CREATE TABLE "SEARCHAPP"."SAVED_FACETED_SEARCH" 
  (	"SAVED_FACETED_SEARCH_ID" NUMBER(*,0) NOT NULL ENABLE, 
"USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"KEYWORDS" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
"CREATE_DT" DATE DEFAULT sysdate, 
"MODIFIED_DT" DATE, 
"SEARCH_TYPE" VARCHAR2(50 BYTE) DEFAULT ('FACETED_SEARCH') NOT NULL ENABLE, 
"ANALYSIS_IDS" VARCHAR2(4000 BYTE), 
 PRIMARY KEY ("SAVED_FACETED_SEARCH_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE, 
 CONSTRAINT "U_SAVED_SEARCH__USER_ID_NAME" UNIQUE ("USER_ID", "NAME")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

--
-- Type: TRIGGER; Owner: SEARCHAPP; Name: TRG_UPD_SAVED_FACETED_SEARCH
--
  CREATE OR REPLACE TRIGGER "SEARCHAPP"."TRG_UPD_SAVED_FACETED_SEARCH" before
  update ON searchapp.saved_faceted_search FOR EACH row 
  BEGIN 
      IF :NEW.modified_dt IS NULL  then
          :NEW.modified_dt := sysdate;
      END IF;
END;

/
ALTER TRIGGER "SEARCHAPP"."TRG_UPD_SAVED_FACETED_SEARCH" ENABLE;
 
--
-- Type: TRIGGER; Owner: SEARCHAPP; Name: TRG_SAVED_FACETED_SEARCH_ID
--
  CREATE OR REPLACE TRIGGER "SEARCHAPP"."TRG_SAVED_FACETED_SEARCH_ID" before
  INSERT ON searchapp.saved_faceted_search FOR EACH row 
  BEGIN 
      IF :NEW.saved_faceted_search_id IS NULL  then
          SELECT SEQ_saved_faceted_search_id.nextval INTO :NEW.saved_faceted_search_id FROM dual;
      END IF;
      IF :NEW.create_dt IS NULL  then
          :NEW.create_dt := sysdate;
      END IF;
END;

/
ALTER TRIGGER "SEARCHAPP"."TRG_SAVED_FACETED_SEARCH_ID" ENABLE;
 
--
-- Type: REF_CONSTRAINT; Owner: SEARCHAPP; Name: SAVED_FACETED_SEARCH_USER_ID
--
ALTER TABLE "SEARCHAPP"."SAVED_FACETED_SEARCH" ADD CONSTRAINT "SAVED_FACETED_SEARCH_USER_ID" FOREIGN KEY ("USER_ID")
 REFERENCES "SEARCHAPP"."SEARCH_AUTH_USER" ("ID") ENABLE;

