--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_A_S_OBJ_ACCESS_BK
--
 CREATE TABLE "SEARCHAPP"."SEARCH_A_S_OBJ_ACCESS_BK" 
  (	"AUTH_SEC_OBJ_ACCESS_ID" NUMBER(18,0), 
"AUTH_PRINCIPAL_ID" NUMBER(18,0), 
"SECURE_OBJECT_ID" NUMBER(18,0), 
"SECURE_ACCESS_LEVEL_ID" NUMBER(18,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

