--
-- Type: TABLE; Owner: SEARCHAPP; Name: TMP_SKW_DUPES
--
 CREATE TABLE "SEARCHAPP"."TMP_SKW_DUPES" 
  (	"ACCESSION" NVARCHAR2(100), 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"UNIQUE_ID" NVARCHAR2(110)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
