--
-- Type: TABLE; Owner: SEARCHAPP; Name: TMP_BIO_ANALYSIS_ATTRIBUTE_LIN
--
 CREATE TABLE "SEARCHAPP"."TMP_BIO_ANALYSIS_ATTRIBUTE_LIN" 
  (	"BIO_ANALYSIS_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
"ANCESTOR_TERM_ID" NUMBER(22,0), 
"ANCESTOR_SEARCH_KEYWORD_ID" NUMBER(38,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
