--
-- Type: TABLE; Owner: TM_WZ; Name: CATEGORY
--
 CREATE TABLE "TM_WZ"."CATEGORY" 
  (	"CATEGORY_CD" VARCHAR2(200 BYTE), 
"CATEGORY_PATH" VARCHAR2(250 BYTE), 
"STUDY_ID" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

