--
-- Type: TABLE; Owner: TM_WZ; Name: I2B2_LOAD_TREE_FULL
--
 CREATE TABLE "TM_WZ"."I2B2_LOAD_TREE_FULL" 
  (	"IDROOT" ROWID, 
"IDCHILD" ROWID, 
 PRIMARY KEY ("IDROOT", "IDCHILD") ENABLE
  ) ORGANIZATION INDEX NOCOMPRESS
 TABLESPACE "USERS" 
PCTTHRESHOLD 50;
