-----------------------------------------------------------------------
--             DO NOT EDIT THIS FILE. IT IS AUTOGENERATED            --
-- Edit the original file in the macroed_functions directory instead --
-----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION tm_cz.i2b2_load_gwas_top50(
    currentJobID bigint DEFAULT null
)
RETURNS BIGINT AS $body$
DECLARE
    newJobFlag    smallint;
    databaseName  varchar(100);
    procedureName varchar(100);
    jobID         bigint;
    stepCt        bigint;
    rowCt         bigint;
    errorNumber   varchar;
    errorMessage  varchar;
BEGIN
    --Set Audit Parameters
    newJobFlag := 0; -- False (Default)
    jobID := currentJobID;
    SELECT current_user INTO databaseName; --(sic)
    procedureName := 'I2B2_LOAD_GWAS_TOP50';

    --Audit JOB Initialization
    --If Job ID does not exist, then this is a single procedure run and we need to create it
    IF (coalesce(jobID::text, '') = '' OR jobID < 1)
        THEN
        newJobFlag := 1; -- True
        SELECT cz_start_audit(procedureName, databaseName) INTO jobID;
    END IF;
    PERFORM cz_write_audit(jobId, databaseName, procedureName,
        'Start FUNCTION', 0, stepCt, 'Done');
    stepCt := 1;

    -- Create temporary table tmp_analysis_gwas_top500
    BEGIN
    DROP TABLE IF EXISTS biomart.tmp_analysis_gwas_top500;
    CREATE TABLE biomart.tmp_analysis_gwas_top500 AS
    SELECT
        a.*
    FROM (
            SELECT
                bio_asy_analysis_gwas_id,
                bio_assay_analysis_id,
                rs_id,
                p_value,
                log_p_value,
                etl_id,
                ext_data,
                p_value_char,
                ROW_NUMBER ( )
                OVER ( PARTITION BY
                        bio_assay_analysis_id
                    ORDER BY
                        p_value ASC,
                        rs_id ASC ) AS rnum
            FROM
                BIOMART.bio_assay_analysis_gwas
        )
        a
    WHERE
        a.rnum <= 500;
    GET DIAGNOSTICS rowCt := ROW_COUNT;
	PERFORM cz_write_audit(jobId, databaseName, procedureName,
        'Create temporary table tmp_analysis_gwas_top500', rowCt, stepCt, 'Done');
    stepCt := stepCt + 1;
    EXCEPTION
        WHEN OTHERS THEN
        errorNumber := SQLSTATE;
        errorMessage := SQLERRM;
        PERFORM cz_error_handler(jobID, procedureName, errorNumber, errorMessage);
        PERFORM cz_end_audit (jobID, 'FAIL');
        RETURN -16;
    END;

    -- Create indexes on tmp_analysis_gwas_top500
    BEGIN
    CREATE INDEX t_a_g_t500_idx ON biomart.tmp_analysis_gwas_top500(rs_id);
    CREATE INDEX t_a_ga_t500_idx ON biomart.tmp_analysis_gwas_top500(bio_assay_analysis_id);
    PERFORM cz_write_audit(jobId, databaseName, procedureName,
        'Create indexes on tmp_analysis_gwas_top500', 0, stepCt, 'Done');
    stepCt := stepCt + 1;
    EXCEPTION
        WHEN OTHERS THEN
        errorNumber := SQLSTATE;
        errorMessage := SQLERRM;
        PERFORM cz_error_handler(jobID, procedureName, errorNumber, errorMessage);
        PERFORM cz_end_audit (jobID, 'FAIL');
        RETURN -16;
    END;

    -- Drop table biomart.bio_asy_analysis_gwas_top50
    BEGIN
    --SELECT COUNT(*) INTO rowCt FROM biomart.bio_asy_analysis_gwas_top50;
    DROP TABLE IF EXISTS biomart.bio_asy_analysis_gwas_top50;
    PERFORM cz_write_audit(jobId, databaseName, procedureName,
        'Drop table biomart.bio_asy_analysis_gwas_top50', rowCt, stepCt, 'Done');
    stepCt := stepCt + 1;
    EXCEPTION
        WHEN OTHERS THEN
        errorNumber := SQLSTATE;
        errorMessage := SQLERRM;
        PERFORM cz_error_handler(jobID, procedureName, errorNumber, errorMessage);
        PERFORM cz_end_audit (jobID, 'FAIL');
        RETURN -16;
    END;

    -- Recreate table biomart.bio_asy_analysis_gwas_top50
    BEGIN
    CREATE TABLE biomart.bio_asy_analysis_gwas_top50 AS
    SELECT
        baa.bio_assay_analysis_id,
        baa.analysis_name AS analysis,
        info.chrom AS chrom,
        info.pos AS pos,
        gmap.snp_name AS rsgene,
        DATA.rs_id AS rsid,
        DATA.p_value AS pvalue,
        DATA.log_p_value AS logpvalue,
        DATA.ext_data AS extdata,
        DATA.rnum
    FROM
        biomart.tmp_analysis_gwas_top500 DATA
        JOIN biomart.bio_assay_analysis baa ON baa.bio_assay_analysis_id = DATA.bio_assay_analysis_id
        JOIN deapp.de_rc_snp_info info ON DATA.rs_id = info.rs_id
            AND ( hg_version = '19' )
        LEFT JOIN deapp.de_snp_gene_map gmap ON gmap.snp_name = info.rs_id;
    GET DIAGNOSTICS rowCt := ROW_COUNT;
	PERFORM cz_write_audit(jobId, databaseName, procedureName,
        'Recreate table biomart.bio_asy_analysis_gwas_top50', rowCt, stepCt, 'Done');
    stepCt := stepCt + 1;
    EXCEPTION
        WHEN OTHERS THEN
        errorNumber := SQLSTATE;
        errorMessage := SQLERRM;
        PERFORM cz_error_handler(jobID, procedureName, errorNumber, errorMessage);
        PERFORM cz_end_audit (jobID, 'FAIL');
        RETURN -16;
    END;

    -- Recreate indexes on biomart.bio_asy_analysis_gwas_top50
    BEGIN
    CREATE INDEX b_asy_gwas_t50_idx1 ON biomart.bio_asy_analysis_gwas_top50(bio_assay_analysis_id) TABLESPACE indx;
    CREATE INDEX b_asy_gwas_t50_idx2 ON biomart.bio_asy_analysis_gwas_top50(analysis) TABLESPACE indx;
    PERFORM cz_write_audit(jobId, databaseName, procedureName,
        'Recreate indexes on biomart.bio_asy_analysis_gwas_top50', 0, stepCt, 'Done');
    stepCt := stepCt + 1;
    EXCEPTION
        WHEN OTHERS THEN
        errorNumber := SQLSTATE;
        errorMessage := SQLERRM;
        PERFORM cz_error_handler(jobID, procedureName, errorNumber, errorMessage);
        PERFORM cz_end_audit (jobID, 'FAIL');
        RETURN -16;
    END;

    -- Cleanup OVERALL JOB if this proc is being run standalone
    IF newJobFlag = 1 THEN
        PERFORM cz_end_audit(jobID, 'SUCCESS');
    END IF;

    RETURN 0;
EXCEPTION
    WHEN OTHERS THEN
        errorNumber := SQLSTATE;
        errorMessage := SQLERRM;
        PERFORM cz_error_handler(jobID, procedureName, errorNumber, errorMessage);
        PERFORM cz_end_audit (jobID, 'FAIL');
        RETURN -16;
END;
$body$
LANGUAGE PLPGSQL;
