--
-- Type: TABLE; Owner: TM_LZ; Name: PATIENT_INFO
--
 CREATE TABLE "TM_LZ"."PATIENT_INFO" 
  (	"STUDY_ID" VARCHAR2(25 BYTE), 
"SITE_ID" VARCHAR2(100 BYTE), 
"SUBJECT_ID" VARCHAR2(50 BYTE), 
"SITE_SUBJ" VARCHAR2(20 BYTE), 
"AGE_IN_YEARS_NUM" NUMBER(3,0), 
"SEX_CD" VARCHAR2(50 BYTE), 
"RACE_CD" VARCHAR2(50 BYTE), 
"TREATMENT_GROUP" VARCHAR2(250 BYTE), 
"USUBJID" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

