--
-- Type: TABLE; Owner: TM_LZ; Name: RWG_ANALYSIS_DATA
--
 CREATE TABLE "TM_LZ"."RWG_ANALYSIS_DATA" 
  (	"STUDY_ID" VARCHAR2(200 BYTE), 
"PROBESET" VARCHAR2(200 BYTE), 
"FOLD_CHANGE" NUMBER(18,5), 
"PVALUE" NUMBER(18,5), 
"RAW_PVALUE" NUMBER(18,5), 
"MIN_LSMEAN" NUMBER(18,5), 
"MAX_LSMEAN" NUMBER(18,5), 
"ANALYSIS_CD" VARCHAR2(255 BYTE), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
"ADJUSTED_PVALUE" NUMBER(18,5)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
