--
-- Type: TABLE; Owner: TM_LZ; Name: STG_CATEGORY
--
 CREATE TABLE "TM_LZ"."STG_CATEGORY" 
  (	"CATEGORY_CD" VARCHAR2(200 BYTE), 
"CATEGORY_PATH" VARCHAR2(250 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
