--
-- Type: TABLE; Owner: TM_LZ; Name: TPM_COUNTS
--
 CREATE TABLE "TM_LZ"."TPM_COUNTS" 
  (	"STUDY_ID" VARCHAR2(25 BYTE), 
"CATEGORY_CD" VARCHAR2(200 BYTE), 
"RECORD_COUNT" NUMBER(18,0), 
"LOAD_DATE" DATE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
