--
-- Name: lz_src_study_metadata; Type: TABLE; Schema: tm_lz; Owner: -
--
CREATE TABLE lz_src_study_metadata (
    study_id character varying(100),
    title character varying(1000),
    description character varying(2000),
    design character varying(2000),
    start_date character varying(50),
    completion_date character varying(50),
    primary_investigator character varying(400),
    contact_field character varying(400),
    status character varying(100),
    overall_design character varying(2000),
    institution character varying(100),
    country character varying(50),
    biomarker_type character varying(255),
    target character varying(255),
    access_type character varying(100),
    study_owner character varying(510),
    study_phase character varying(100),
    blinding_procedure character varying(1000),
    studytype character varying(510),
    duration_of_study_weeks character varying(200),
    number_of_patients character varying(200),
    number_of_sites character varying(200),
    route_of_administration character varying(510),
    dosing_regimen character varying(3500),
    group_assignment character varying(510),
    type_of_control character varying(510),
    primary_end_points character varying(2000),
    secondary_end_points character varying(3500),
    inclusion_criteria character varying(4000),
    exclusion_criteria character varying(4000),
    subjects character varying(2000),
    gender_restriction_mfb character varying(510),
    min_age character varying(100),
    max_age character varying(100),
    secondary_ids character varying(510),
    development_partner character varying(100),
    geo_platform character varying(100),
    main_findings character varying(2000),
    search_area character varying(100),
    compound character varying(1000),
    disease character varying(1000),
    pubmed_ids character varying(1000),
    organism character varying(200),
    upload_date timestamp without time zone
);

