--
-- Type: TABLE; Owner: DEAPP; Name: DE_RC_SNP_INFO
--
 CREATE TABLE "DEAPP"."DE_RC_SNP_INFO" 
  (	"SNP_INFO_ID" NUMBER(22,0), 
"RS_ID" NVARCHAR2(50), 
"CHROM" VARCHAR2(4 BYTE), 
"POS" NUMBER(10,0), 
"REF" VARCHAR2(1000 BYTE), 
"ALT" VARCHAR2(1000 BYTE), 
"GENE_INFO" VARCHAR2(1000 BYTE), 
"VARIATION_CLASS" VARCHAR2(10 BYTE), 
"STRAND" VARCHAR2(1 BYTE), 
"CLINSIG" VARCHAR2(100 BYTE), 
"DISEASE" VARCHAR2(500 BYTE), 
"GMAF" NUMBER(10,0), 
"GENE_BIOTYPE" VARCHAR2(100 BYTE), 
"IMPACT" VARCHAR2(50 BYTE), 
"TRANSCRIPT_ID" VARCHAR2(100 BYTE), 
"FUNCTIONAL_CLASS" VARCHAR2(100 BYTE), 
"EFFECT" VARCHAR2(100 BYTE), 
"EXON_ID" VARCHAR2(100 BYTE), 
"AMINO_ACID_CHANGE" VARCHAR2(50 BYTE), 
"CODON_CHANGE" VARCHAR2(100 BYTE), 
"HG_VERSION" VARCHAR2(10 BYTE), 
"GENE_NAME" VARCHAR2(50 BYTE), 
"ENTREZ_ID" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

