--
-- Type: TABLE; Owner: DEAPP; Name: DE_SNP_CALLS_BY_GSM
--
 CREATE TABLE "DEAPP"."DE_SNP_CALLS_BY_GSM" 
  (	"GSM_NUM" VARCHAR2(10 BYTE), 
"PATIENT_NUM" NUMBER(20,0), 
"SNP_NAME" VARCHAR2(100 BYTE), 
"SNP_CALLS" VARCHAR2(4 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

