--
-- Type: TABLE; Owner: DEAPP; Name: DE_SNP_LOADING_TEMP
--
 CREATE TABLE "DEAPP"."DE_SNP_LOADING_TEMP" 
  (	"SNP_TEMP_ID" NUMBER(22,0), 
"NAME" VARCHAR2(255 BYTE), 
"CHROM" VARCHAR2(16 BYTE), 
"CHROM_POS" NUMBER(22,0), 
"PROBE_NAME" VARCHAR2(255 BYTE), 
"ENTREZ_GENE_STRING" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
