--
-- Type: SEQUENCE; Owner: DEAPP; Name: SEQ_VARIANT_POPULATION_DATA_ID
--
CREATE SEQUENCE  "DEAPP"."SEQ_VARIANT_POPULATION_DATA_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_POPULATION_DATA
--
 CREATE TABLE "DEAPP"."DE_VARIANT_POPULATION_DATA" 
  (	"VARIANT_POPULATION_DATA_ID" NUMBER(22,0), 
"DATASET_ID" VARCHAR2(50 BYTE), 
"CHR" VARCHAR2(50 BYTE), 
"POS" NUMBER(18,0), 
"INFO_NAME" VARCHAR2(100 BYTE), 
"INFO_INDEX" NUMBER DEFAULT 0, 
"INTEGER_VALUE" NUMBER(22,0), 
"FLOAT_VALUE" NUMBER, 
"TEXT_VALUE" VARCHAR2(4000 BYTE), 
 CONSTRAINT "DE_VARIANT_POPULATION_DATA_PK" PRIMARY KEY ("VARIANT_POPULATION_DATA_ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" ;

--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_VARIANT_POPULATION_DATA_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_VARIANT_POPULATION_DATA_ID" 
before insert on DEAPP.DE_VARIANT_POPULATION_DATA
for each row
begin
   if inserting then
      if :NEW.VARIANT_POPULATION_DATA_ID is null then
         select DEAPP.SEQ_VARIANT_POPULATION_DATA_ID.nextval into :NEW.VARIANT_POPULATION_DATA_ID from dual;
      end if;
  end if;
end;
/
ALTER TRIGGER "DEAPP"."TRG_VARIANT_POPULATION_DATA_ID" ENABLE;
 
--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0045256
--
ALTER TABLE "DEAPP"."DE_VARIANT_POPULATION_DATA" ADD FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

