--
-- Type: SEQUENCE; Owner: DEAPP; Name: SEQ_VARIANT_POPULATION_INFO_ID
--
CREATE SEQUENCE  "DEAPP"."SEQ_VARIANT_POPULATION_INFO_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_POPULATION_INFO
--
 CREATE TABLE "DEAPP"."DE_VARIANT_POPULATION_INFO" 
  (	"VARIANT_POPULATION_INFO_ID" NUMBER(22,0), 
"DATASET_ID" VARCHAR2(50 BYTE), 
"INFO_NAME" VARCHAR2(100 BYTE), 
"DESCRIPTION" VARCHAR2(4000 BYTE), 
"TYPE" VARCHAR2(30 BYTE), 
"number" VARCHAR2(10 BYTE), 
 CONSTRAINT "DE_VARIANT_POPULATION_INFO_PK" PRIMARY KEY ("VARIANT_POPULATION_INFO_ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" ;

--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_VARIANT_POPULATION_INFO_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_VARIANT_POPULATION_INFO_ID" 
before insert on DEAPP.DE_VARIANT_POPULATION_INFO
for each row
begin
   if inserting then
      if :NEW.VARIANT_POPULATION_INFO_ID is null then
         select DEAPP.SEQ_VARIANT_POPULATION_INFO_ID.nextval into :NEW.VARIANT_POPULATION_INFO_ID from dual;
      end if;
  end if;
end;
/
ALTER TRIGGER "DEAPP"."TRG_VARIANT_POPULATION_INFO_ID" ENABLE;
 
--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0045254
--
ALTER TABLE "DEAPP"."DE_VARIANT_POPULATION_INFO" ADD FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

