--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_SUBJECT_DETAIL
--
 CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" 
  (	"VARIANT_SUBJECT_DETAIL_ID" NUMBER(9,0), 
"DATASET_ID" VARCHAR2(50 BYTE), 
"CHR" VARCHAR2(50 BYTE), 
"POS" NUMBER(20,0), 
"RS_ID" VARCHAR2(50 BYTE), 
"REF" VARCHAR2(100 BYTE), 
"ALT" VARCHAR2(100 BYTE), 
"QUAL" VARCHAR2(100 BYTE), 
"FILTER" VARCHAR2(50 BYTE), 
"INFO" VARCHAR2(2000 BYTE), 
"FORMAT" VARCHAR2(50 BYTE), 
"VARIANT_VALUE" CLOB, 
 PRIMARY KEY ("VARIANT_SUBJECT_DETAIL_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE, 
 CONSTRAINT "VARIANT_SUBJECT_DETAIL_UK" UNIQUE ("DATASET_ID", "CHR", "POS", "RS_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" 
LOB ("VARIANT_VALUE") STORE AS BASICFILE (
 TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) 
 CACHE ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: VARIANT_SUBJECT_DETAIL_FK
--
ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ADD CONSTRAINT "VARIANT_SUBJECT_DETAIL_FK" FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_VARIANT_SUB_DT_IDX1
--
CREATE INDEX "DEAPP"."DE_VARIANT_SUB_DT_IDX1" ON "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ("DATASET_ID", "RS_ID")
TABLESPACE "USERS" ;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_VARIANT_SUB_DETAIL_IDX2
--
CREATE INDEX "DEAPP"."DE_VARIANT_SUB_DETAIL_IDX2" ON "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ("DATASET_ID", "CHR")
TABLESPACE "USERS" ;

