--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_SUBJECT_SUMMARY
--
 CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" 
  (	"VARIANT_SUBJECT_SUMMARY_ID" NUMBER(9,0), 
"CHR" VARCHAR2(50 BYTE), 
"POS" NUMBER(20,0), 
"DATASET_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"SUBJECT_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"RS_ID" VARCHAR2(50 BYTE), 
"VARIANT" VARCHAR2(100 BYTE), 
"VARIANT_FORMAT" VARCHAR2(100 BYTE), 
"VARIANT_TYPE" VARCHAR2(100 BYTE), 
 PRIMARY KEY ("VARIANT_SUBJECT_SUMMARY_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE, 
 CONSTRAINT "VARIANT_SUBJECT_SUMMARY_UK" UNIQUE ("DATASET_ID", "CHR", "POS", "RS_ID", "SUBJECT_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: VARIANT_SUBJECT_SUMMARY_FK
--
ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" ADD CONSTRAINT "VARIANT_SUBJECT_SUMMARY_FK" FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

