--
-- Type: SEQUENCE; Owner: DEAPP; Name: DE_VARIANT_SUBJECT_SUMMARY_SEQ
--
CREATE SEQUENCE  "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_SUBJECT_SUMMARY
--
 CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" 
  (	"VARIANT_SUBJECT_SUMMARY_ID" NUMBER(22,0), 
"CHR" VARCHAR2(50 BYTE), 
"POS" NUMBER(22,0), 
"DATASET_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"SUBJECT_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"RS_ID" VARCHAR2(50 BYTE), 
"VARIANT" VARCHAR2(1000 BYTE), 
"VARIANT_FORMAT" VARCHAR2(100 BYTE), 
"VARIANT_TYPE" VARCHAR2(100 BYTE), 
"REFERENCE" CHAR(1 BYTE), 
"ALLELE1" NUMBER(5,0), 
"ALLELE2" NUMBER(5,0), 
"ASSAY_ID" NUMBER(18,0), 
 CHECK ( reference in ('T', 'F') ) ENABLE, 
 CONSTRAINT "VARIANT_SUBJECT_SUMMARY_ID" PRIMARY KEY ("VARIANT_SUBJECT_SUMMARY_ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "DEAPP" ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0045383
--
ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" ADD FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_VARIANT_SUBJECT_SUMMARY_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_VARIANT_SUBJECT_SUMMARY_ID" 
before insert on DEAPP.DE_VARIANT_SUBJECT_SUMMARY
for each row
begin
   if inserting then
      if :NEW.variant_subject_summary_id is null then
         select DEAPP.DE_VARIANT_SUBJECT_SUMMARY_SEQ.nextval into :NEW.variant_subject_summary_id from dual;
      end if;
  end if;
end;
/
ALTER TRIGGER "DEAPP"."TRG_VARIANT_SUBJECT_SUMMARY_ID" ENABLE;
 
