--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_SUBJECT_IDX
--
 CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_IDX" 
  (	"DATASET_ID" VARCHAR2(50 BYTE), 
"SUBJECT_ID" VARCHAR2(50 BYTE), 
"POSITION" NUMBER(10,0), 
"VARIANT_SUBJECT_IDX_ID" NUMBER(18,0), 
 CONSTRAINT "VARIANT_SUBJECT_IDX_UK" UNIQUE ("DATASET_ID", "SUBJECT_ID", "POSITION")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: VARIANT_SUBJECT_IDX_FK
--
ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_IDX" ADD CONSTRAINT "VARIANT_SUBJECT_IDX_FK" FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

