--
-- Type: SEQUENCE; Owner: DEAPP; Name: DE_VARIANT_SUBJECT_DETAIL_SEQ
--
CREATE SEQUENCE  "DEAPP"."DE_VARIANT_SUBJECT_DETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_SUBJECT_DETAIL
--
 CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" 
  (	"VARIANT_SUBJECT_DETAIL_ID" NUMBER(22,0) NOT NULL ENABLE, 
"DATASET_ID" VARCHAR2(50 BYTE), 
"CHR" VARCHAR2(50 BYTE), 
"POS" NUMBER(22,0), 
"RS_ID" VARCHAR2(50 BYTE), 
"REF" VARCHAR2(500 BYTE), 
"ALT" VARCHAR2(500 BYTE), 
"QUAL" VARCHAR2(100 BYTE), 
"FILTER" VARCHAR2(50 BYTE), 
"INFO" VARCHAR2(4000 BYTE), 
"FORMAT" VARCHAR2(500 BYTE), 
"VARIANT_VALUE" CLOB, 
 CONSTRAINT "VARIANT_SUBJECT_DETAIL_ID_PK" PRIMARY KEY ("VARIANT_SUBJECT_DETAIL_ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" 
LOB ("VARIANT_VALUE") STORE AS BASICFILE (
 TABLESPACE "DEAPP" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_VARIANT_SUBJECT_DETAIL_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_VARIANT_SUBJECT_DETAIL_ID" 
before insert on DEAPP.de_variant_subject_detail
for each row
begin
   if inserting then
      if :NEW.variant_subject_detail_id is null then
         select DEAPP.DE_VARIANT_SUBJECT_DETAIL_SEQ.nextval into :NEW.variant_subject_detail_id from dual;
      end if;
  end if;
end;
/
ALTER TRIGGER "DEAPP"."TRG_VARIANT_SUBJECT_DETAIL_ID" ENABLE;
 
--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0045377
--
ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ADD FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

