--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_METADATA
--
 CREATE TABLE "DEAPP"."DE_VARIANT_METADATA" 
  (	"DE_VARIANT_METADATA_ID" NUMBER(22,0), 
"DATASET_ID" VARCHAR2(50 BYTE), 
"KEY" VARCHAR2(255 BYTE), 
"VALUE" CLOB, 
 CONSTRAINT "DE_VARIANT_METADATA_PK" PRIMARY KEY ("DE_VARIANT_METADATA_ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" 
LOB ("VALUE") STORE AS BASICFILE (
 TABLESPACE "DEAPP" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

--
-- Type: SEQUENCE; Owner: DEAPP; Name: SEQ_DE_VARIANT_METADATA_ID
--
CREATE SEQUENCE  "DEAPP"."SEQ_DE_VARIANT_METADATA_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_DE_VARIANT_METADATA_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_DE_VARIANT_METADATA_ID" 
before insert on DEAPP.DE_VARIANT_METADATA
for each row
begin
   if inserting then
      if :NEW.DE_VARIANT_METADATA_ID is null then
         select DEAPP.SEQ_DE_VARIANT_METADATA_ID.nextval into :NEW.DE_VARIANT_METADATA_ID from dual;
      end if;
  end if;
end;
/
ALTER TRIGGER "DEAPP"."TRG_DE_VARIANT_METADATA_ID" ENABLE;
 
--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0045252
--
ALTER TABLE "DEAPP"."DE_VARIANT_METADATA" ADD FOREIGN KEY ("DATASET_ID")
 REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;

