--
-- Type: TABLE; Owner: DEAPP; Name: DEAPP_PROBESET
--
 CREATE TABLE "DEAPP"."DEAPP_PROBESET" 
  (	"PROBESET_ID" NUMBER(38,0) NOT NULL ENABLE, 
"PROBESET" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"PLATFORM" VARCHAR2(100 BYTE) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

