--
-- Type: TABLE; Owner: DEAPP; Name: ET$000A126A0001
--
 CREATE TABLE "DEAPP"."ET$000A126A0001" 
  (	"SNP_DATA_BY_PROBE_ID" NUMBER(22,0), 
"PROBE_ID" NUMBER(22,0), 
"PROBE_NAME" VARCHAR2(255 BYTE), 
"SNP_ID" NUMBER(22,0), 
"SNP_NAME" VARCHAR2(255 BYTE), 
"TRIAL_NAME" VARCHAR2(255 BYTE), 
"DATA_BY_PROBE" CLOB
  ) 
  ORGANIZATION EXTERNAL 
   ( TYPE ORACLE_DATAPUMP
     DEFAULT DIRECTORY "DATA_PUMP_DIR"
     ACCESS PARAMETERS
     ( DEBUG = (0 , 0) DATAPUMP INTERNAL TABLE "DEAPP"."DE_SNP_DATA_BY_PROBE"  JOB ( "DEAPP","SYS_IMPORT_FULL_01",2) WORKERID 1 PARALLEL 1 VERSION '11.1.0.0.0' ENCRYPTPASSWORDISNULL  COMPRESSION DISABLED  ENCRYPTION DISABLED             )
     LOCATION
      ( 'bogus.dat'
      )
   )
  REJECT LIMIT UNLIMITED;

