--
-- Type: TABLE; Owner: DEAPP; Name: SNP_GENE
--
 CREATE TABLE "DEAPP"."SNP_GENE" 
  (	"SNP_ID" VARCHAR2(130 BYTE), 
"GENE_ID" VARCHAR2(20 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

