--
-- Type: TABLE; Owner: I2B2METADATA; Name: I2B2_TAG_OPTIONS
--
 CREATE TABLE "I2B2METADATA"."I2B2_TAG_OPTIONS"
  (	"TAG_OPTION_ID" NUMBER DEFAULT i2b2metadata.i2b2_tag_options_id_seq.NEXTVAL,
"TAG_TYPE_ID" NUMBER(18,0) NOT NULL ENABLE,
"VALUE" VARCHAR2(1000 BYTE),
 CONSTRAINT "I2B2_TAG_OPTIONS_PKEY" PRIMARY KEY ("TAG_OPTION_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: REF_CONSTRAINT; Owner: I2B2METADATA; Name: I2B2_TAG_OPTIONS_TAG_TYPE_FK
--
ALTER TABLE "I2B2METADATA"."I2B2_TAG_OPTIONS" ADD CONSTRAINT "I2B2_TAG_OPTIONS_TAG_TYPE_FK" FOREIGN KEY ("TAG_TYPE_ID")
 REFERENCES "I2B2METADATA"."I2B2_TAG_TYPES" ("TAG_TYPE_ID") ENABLE;
