--
-- Type: TABLE; Owner: I2B2METADATA; Name: I2B2_TAG_TYPES
--
 CREATE TABLE "I2B2METADATA"."I2B2_TAG_TYPES"
  (	"TAG_TYPE_ID" NUMBER(18,0) DEFAULT i2b2metadata.i2b2_tag_types_tag_type_id_seq.NEXTVAL NOT NULL ENABLE,
"TAG_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"SOLR_FIELD_NAME" VARCHAR2(255 BYTE),
"NODE_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"VALUE_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"SHOWN_IF_EMPTY" CHAR(1 BYTE) NOT NULL ENABLE,
"index" NUMBER,
 CONSTRAINT "I2B2_TAG_TYPES_NODE_TAG_KEY" UNIQUE ("NODE_TYPE", "TAG_TYPE")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE,
 CONSTRAINT "I2B2_TAG_TYPES_PKEY" PRIMARY KEY ("TAG_TYPE_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
