--
-- Type: TABLE; Owner: I2B2METADATA; Name: SECURE_OBJ_TOKEN_FIX
--
 CREATE TABLE "I2B2METADATA"."SECURE_OBJ_TOKEN_FIX" 
  (	"RIGHT_TOKEN" VARCHAR2(50 BYTE), 
"SECURE_OBJ_TOKEN" VARCHAR2(50 BYTE), 
"C_FULLNAME" VARCHAR2(900 BYTE) NOT NULL ENABLE, 
"TRIAL_ID" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
