--
-- Type: TABLE; Owner: BIOMART; Name: ASSAY_ANALYSIS_DATA
--
 CREATE TABLE "BIOMART"."ASSAY_ANALYSIS_DATA" 
  (	"BIO_ASY_ANALYSIS_DATA_ID" NUMBER(*,0), 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"BIO_ASSAY_PLATFORM_ID" NUMBER(18,0) NOT NULL ENABLE, 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
"BIO_ASSAY_FEATURE_GROUP_ID" NUMBER(18,0) NOT NULL ENABLE, 
"FEATURE_GROUP_NAME" VARCHAR2(100 BYTE), 
"FOLD_CHANGE_RATIO" NUMBER(22,10), 
"RAW_PVALUE" NUMBER(22,10), 
"ADJUSTED_PVALUE" NUMBER(22,10), 
"PREFERRED_PVALUE" NUMBER(22,10), 
"TEA_NORMALIZED_PVALUE" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

