--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ANALYSIS_ATTRIBUTE
--
 CREATE TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" 
  (	"STUDY_ID" VARCHAR2(255 BYTE), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"TERM_ID" NUMBER(22,0), 
"SOURCE_CD" VARCHAR2(255 BYTE), 
"BIO_ANALYSIS_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "PK_BAA_ID" PRIMARY KEY ("BIO_ANALYSIS_ATTRIBUTE_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
--
-- Type: TRIGGER; Owner: BIOMART; Name: TRG_BIO_ANALYSIS_ATTRIBUTE_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATTRIBUTE_ID" 
before insert on "BIO_ANALYSIS_ATTRIBUTE"    
for each row begin     
	if inserting then       
		if :NEW."BIO_ANALYSIS_ATTRIBUTE_ID" is null 
		then select SEQ_BIO_DATA_ID.nextval into :NEW."BIO_ANALYSIS_ATTRIBUTE_ID" from dual;       end if;    end if; end;

/
ALTER TRIGGER "BIOMART"."TRG_BIO_ANALYSIS_ATTRIBUTE_ID" ENABLE;
