--
-- Type: TABLE; Owner: BIOMART; Name: BIO_SPECIES_ORGANISM
--
 CREATE TABLE "BIOMART"."BIO_SPECIES_ORGANISM" 
  (	"ID" NUMBER NOT NULL ENABLE, 
"SPECIES" NVARCHAR2(200), 
"ORGANISM" NVARCHAR2(200), 
 PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
