--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ANALYSIS_ATTRIBUTE_LINEAGE
--
 CREATE TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" 
  (	"BIO_ANALYSIS_ATT_LINEAGE_ID" NUMBER NOT NULL ENABLE, 
"BIO_ANALYSIS_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
"ANCESTOR_TERM_ID" NUMBER NOT NULL ENABLE, 
"ANCESTOR_SEARCH_KEYWORD_ID" NUMBER NOT NULL ENABLE, 
 CONSTRAINT "PK_BAAL_ID" PRIMARY KEY ("BIO_ANALYSIS_ATT_LINEAGE_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
--
-- Type: TRIGGER; Owner: BIOMART; Name: TRG_BIO_ANLY_ATT_LINEAGE_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_ANLY_ATT_LINEAGE_ID" 
before insert on "BIO_ANALYSIS_ATTRIBUTE_LINEAGE"    
for each row begin     
	if inserting then       
		if :NEW."BIO_ANALYSIS_ATT_LINEAGE_ID" is null 
		then select SEQ_BIO_DATA_ID.nextval into :NEW."BIO_ANALYSIS_ATT_LINEAGE_ID" from dual;       end if;    end if; end;

/
ALTER TRIGGER "BIOMART"."TRG_BIO_ANLY_ATT_LINEAGE_ID" ENABLE;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: FK_BAAL_BAA
--
ALTER TABLE "BIOMART"."BIO_ANALYSIS_ATTRIBUTE_LINEAGE" ADD CONSTRAINT "FK_BAAL_BAA" FOREIGN KEY ("BIO_ANALYSIS_ATTRIBUTE_ID")
 REFERENCES "BIOMART"."BIO_ANALYSIS_ATTRIBUTE" ("BIO_ANALYSIS_ATTRIBUTE_ID") ENABLE;
