--
-- Type: TABLE; Owner: BIOMART; Name: BIO_MARKER_EXP_ANALYSIS_MV
--
 CREATE TABLE "BIOMART"."BIO_MARKER_EXP_ANALYSIS_MV" 
  (	"BIO_MARKER_ID" NUMBER(18,0), 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
"MV_ID" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" 
 PARALLEL 4 ;

--
-- Type: INDEX; Owner: BIOMART; Name: B_M_E_ALS_MV_BK_IDX
--
CREATE INDEX "BIOMART"."B_M_E_ALS_MV_BK_IDX" ON "BIOMART"."BIO_MARKER_EXP_ANALYSIS_MV" ("BIO_MARKER_ID")
TABLESPACE "USERS" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BMEAMV_EXPERIMENT_ID
--
CREATE INDEX "BIOMART"."BMEAMV_EXPERIMENT_ID" ON "BIOMART"."BIO_MARKER_EXP_ANALYSIS_MV" ("BIO_EXPERIMENT_ID")
TABLESPACE "USERS" ;

