--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_DATA
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" 
  (	"BIO_ASY_ANALYSIS_DATA_ID" NUMBER NOT NULL ENABLE, 
"FOLD_CHANGE_RATIO" NUMBER, 
"RAW_PVALUE" NUMBER(32,15), 
"ADJUSTED_PVALUE" NUMBER(32,15), 
"R_VALUE" NUMBER(32,15), 
"RHO_VALUE" NUMBER(32,15), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"ADJUSTED_P_VALUE_CODE" NVARCHAR2(100), 
"FEATURE_GROUP_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"BIO_ASSAY_PLATFORM_ID" NUMBER(18,0), 
"ETL_ID" NVARCHAR2(100), 
"PREFERRED_PVALUE" NUMBER(32,15), 
"CUT_VALUE" NUMBER(32,15), 
"RESULTS_VALUE" NVARCHAR2(100), 
"NUMERIC_VALUE" NUMBER(32,15), 
"NUMERIC_VALUE_CODE" NVARCHAR2(50), 
"TEA_NORMALIZED_PVALUE" NUMBER(32,15), 
"BIO_ASSAY_FEATURE_GROUP_ID" NUMBER(18,0), 
"LSMEAN1" NUMBER(9,2), 
"LSMEAN2" NUMBER(9,2)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_PLATFORM
--
CREATE INDEX "BIOMART"."IDX_BAAD_PLATFORM" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_PLATFORM_ID")
TABLESPACE "USERS" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_ANALYSIS
--
CREATE INDEX "BIOMART"."IDX_BAAD_ANALYSIS" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_ANALYSIS_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "USERS" ;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_DATA_N_FK3
--
ALTER TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ADD CONSTRAINT "BIO_ASSAY_ANALYSIS_DATA_N_FK3" FOREIGN KEY ("BIO_ASSAY_PLATFORM_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_PLATFORM" ("BIO_ASSAY_PLATFORM_ID") ENABLE;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_DATA_N_FK2
--
ALTER TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ADD CONSTRAINT "BIO_ASSAY_ANALYSIS_DATA_N_FK2" FOREIGN KEY ("BIO_EXPERIMENT_ID")
 REFERENCES "BIOMART"."BIO_EXPERIMENT" ("BIO_EXPERIMENT_ID") ENABLE;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_DATA_N_FK1
--
ALTER TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ADD CONSTRAINT "BIO_ASSAY_ANALYSIS_DATA_N_FK1" FOREIGN KEY ("BIO_ASSAY_ANALYSIS_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_ANALYSIS" ("BIO_ASSAY_ANALYSIS_ID") ENABLE;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_EXPERIMENT_ANALYSIS1
--
CREATE INDEX "BIOMART"."IDX_BAAD_EXPERIMENT_ANALYSIS1" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "USERS" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_ANALYSIS_PROBE
--
CREATE INDEX "BIOMART"."IDX_BAAD_ANALYSIS_PROBE" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_ANALYSIS_ID", "BIO_ASSAY_FEATURE_GROUP_ID")
TABLESPACE "USERS" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_PROBE1
--
CREATE INDEX "BIOMART"."IDX_BAAD_PROBE1" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("FEATURE_GROUP_NAME", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "USERS" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_EAP
--
CREATE INDEX "BIOMART"."IDX_BAAD_EAP" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID", "BIO_ASSAY_FEATURE_GROUP_ID")
TABLESPACE "USERS" ;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: BIO_ASY_AD_FG_FK
--
ALTER TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ADD CONSTRAINT "BIO_ASY_AD_FG_FK" FOREIGN KEY ("BIO_ASSAY_FEATURE_GROUP_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_FEATURE_GROUP" ("BIO_ASSAY_FEATURE_GROUP_ID") ENABLE;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_PROBE
--
CREATE INDEX "BIOMART"."IDX_BAAD_PROBE" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("FEATURE_GROUP_NAME")
TABLESPACE "USERS" ;
--
-- Type: TRIGGER; Owner: BIOMART; Name: TRIG_BIO_ASY_ANALYSIS_DATA_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART"."TRIG_BIO_ASY_ANALYSIS_DATA_ID" 
  BEFORE INSERT ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA"
  REFERENCING FOR EACH ROW
  BEGIN
  if inserting then       
    if :NEW."BIO_ASY_ANALYSIS_DATA_ID" is null 
    then  select SEQ_BIO_DATA_ID.nextval into :NEW."BIO_ASY_ANALYSIS_DATA_ID" from dual;       
    end if;    
    end if;
END;
/
ALTER TRIGGER "BIOMART"."TRIG_BIO_ASY_ANALYSIS_DATA_ID" ENABLE;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BAAD_EXPERIMENT_ANALYSIS
--
CREATE INDEX "BIOMART"."IDX_BAAD_EXPERIMENT_ANALYSIS" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID")
TABLESPACE "USERS" ;
