--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_COHORT
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_COHORT" 
  (	"STUDY_ID" VARCHAR2(500 BYTE), 
"COHORT_ID" VARCHAR2(500 BYTE), 
"DISEASE" VARCHAR2(500 BYTE), 
"SAMPLE_TYPE" VARCHAR2(500 BYTE), 
"TREATMENT" VARCHAR2(500 BYTE), 
"ORGANISM" VARCHAR2(500 BYTE), 
"PATHOLOGY" VARCHAR2(500 BYTE), 
"COHORT_TITLE" VARCHAR2(500 BYTE), 
"SHORT_DESC" VARCHAR2(500 BYTE), 
"LONG_DESC" VARCHAR2(500 BYTE), 
"IMPORT_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
"BIO_ASSAY_COHORT_ID" NUMBER(38,0) NOT NULL ENABLE, 
 CONSTRAINT "PK_BIO_ASSAY_COHORT" PRIMARY KEY ("BIO_ASSAY_COHORT_ID")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
--
-- Type: TRIGGER; Owner: BIOMART; Name: TRG_BIO_ASSAY_COHORT_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_ASSAY_COHORT_ID" 
before insert on "BIO_ASSAY_COHORT"    
for each row 
  begin     
    if inserting then      
      if :NEW."BIO_ASSAY_COHORT_ID" is null 
      then  select SEQ_BIO_DATA_ID.nextval into :NEW."BIO_ASSAY_COHORT_ID" from dual;       
      end if;   
      end if; 
      end;

/
ALTER TRIGGER "BIOMART"."TRG_BIO_ASSAY_COHORT_ID" ENABLE;
