--
-- Type: TABLE; Owner: BIOMART; Name: GPL_ANNOTATION
--
 CREATE TABLE "BIOMART"."GPL_ANNOTATION" 
  (	"PLATFORM" VARCHAR2(100 BYTE), 
"SPECIES" VARCHAR2(100 BYTE), 
"PROBE_ID" VARCHAR2(100 BYTE), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_DESCR" VARCHAR2(1000 BYTE), 
"GENE_ID" VARCHAR2(20 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

