--
-- Type: TABLE; Owner: BIOMART; Name: GSE_ANALYSIS
--
 CREATE TABLE "BIOMART"."GSE_ANALYSIS" 
  (	"NAME" VARCHAR2(100 BYTE), 
"PLATFORM" VARCHAR2(100 BYTE), 
"TEST" VARCHAR2(500 BYTE), 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
"BIO_ASSAY_PLATFORM_ID" NUMBER(18,0) NOT NULL ENABLE, 
"DATA_CNT" NUMBER, 
"FC_MEAN" NUMBER, 
"FC_STDDEV" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
