--
-- Type: TABLE; Owner: BIOMART; Name: PROJECT_INFO
--
 CREATE TABLE "BIOMART"."PROJECT_INFO" 
  (	"NAME" VARCHAR2(100 BYTE), 
"FILE_NAME" VARCHAR2(100 BYTE), 
"ACTIVEDATANAME" VARCHAR2(400 BYTE), 
"PROJECT_ACCESSION" VARCHAR2(100 BYTE), 
"PROJECT_CATEGORY" CLOB, 
"PROJECT_CONTACTADDRESS" VARCHAR2(4000 BYTE), 
"PROJECT_CONTACTCOMPANY" VARCHAR2(400 BYTE), 
"PROJECT_CONTACTDEPARTMENT" VARCHAR2(400 BYTE), 
"PROJECT_CONTACTEMAIL" VARCHAR2(400 BYTE), 
"PROJECT_CONTACTLABORATORY" VARCHAR2(400 BYTE), 
"PROJECT_CONTACTNAME" VARCHAR2(400 BYTE), 
"PROJECT_CONTACTPHONE" VARCHAR2(100 BYTE), 
"PROJECT_CONTACTWEBLINK" VARCHAR2(1000 BYTE), 
"PROJECT_CONTRIBUTORS" VARCHAR2(4000 BYTE), 
"PROJECT_DESCRIPTION" CLOB, 
"PROJECT_DESIGN" CLOB, 
"PROJECT_ID" VARCHAR2(100 BYTE), 
"PROJECT_KEYWORDS" VARCHAR2(1000 BYTE), 
"PROJECT_ORGANISM" VARCHAR2(800 BYTE), 
"PROJECT_TISSUE" VARCHAR2(400 BYTE), 
"PROJECT_COMPOUND" VARCHAR2(400 BYTE), 
"PROJECT_PLATFORM" VARCHAR2(400 BYTE), 
"PROJECT_PLATFORMDESCRIPTION" VARCHAR2(4000 BYTE), 
"PROJECT_PLATFORMORGANISM" VARCHAR2(400 BYTE), 
"PROJECT_PLATFORMPROVIDER" VARCHAR2(400 BYTE), 
"PROJECT_PLATFORMTECHNOLOGY" VARCHAR2(400 BYTE), 
"PROJECT_PLATFORMTYPE" VARCHAR2(400 BYTE), 
"PROJECT_PUBMED" VARCHAR2(400 BYTE), 
"PROJECT_STUDYTYPE" VARCHAR2(1000 BYTE), 
"PROJECT_SUPPLEMENTARYFILE" VARCHAR2(400 BYTE), 
"PROJECT_TITLE" VARCHAR2(500 BYTE), 
"PROJECT_WEBLINK" VARCHAR2(1000 BYTE), 
"PROJECT_EXTRACTEDFROMCELFILES" VARCHAR2(1000 BYTE), 
"PROJECT_CONTACTORGANIZATION" NVARCHAR2(1000), 
"PROJECT_CONTACTFAX" VARCHAR2(100 BYTE), 
"PROJECT_OUTPUTFILE" VARCHAR2(500 BYTE), 
"PROJECT_DATASOURCE" NVARCHAR2(100), 
"PROJECT_EDITORS" VARCHAR2(100 BYTE), 
"PROJECT_ISPRIVATE" VARCHAR2(100 BYTE), 
"PROJECT_PUBLISHDATE" VARCHAR2(100 BYTE), 
"ENTRYDT" DATE, 
"KEY" VARCHAR2(4000 BYTE), 
"PROJECT_BATCHNAME" VARCHAR2(4000 BYTE), 
"PROJECT_BIOPROJECT" VARCHAR2(4000 BYTE), 
"PROJECT_COMMENTS" VARCHAR2(4000 BYTE), 
"PROJECT_DATECURATED" VARCHAR2(4000 BYTE), 
"PROJECT_DATESTUDYMODIFIED" VARCHAR2(4000 BYTE), 
"PROJECT_DATESTUDYRELEASED" VARCHAR2(4000 BYTE), 
"PROJECT_DATESTUDYSUBMISSION" VARCHAR2(4000 BYTE), 
"PROJECT_OVERALLDESIGN" VARCHAR2(4000 BYTE), 
"PROJECT_SAMPLECOUNT" VARCHAR2(4000 BYTE), 
"PROJECT_THERAPEUTICAREA" VARCHAR2(4000 BYTE), 
"PROJECT_TREATMENT" VARCHAR2(4000 BYTE), 
"PROJECT_DISEASE" VARCHAR2(4000 BYTE), 
"PROJECT_SUPERSERIES" VARCHAR2(4000 BYTE), 
"PROJECT_EXPERIMENTTYPE" VARCHAR2(4000 BYTE), 
"PROJECT_EXPFACTORS" VARCHAR2(4000 BYTE), 
 PRIMARY KEY ("NAME")
 USING INDEX
 TABLESPACE "USERS"  ENABLE, 
 UNIQUE ("FILE_NAME")
 USING INDEX
 TABLESPACE "USERS"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" 
LOB ("PROJECT_CATEGORY") STORE AS BASICFILE (
 TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE NOLOGGING ) 
LOB ("PROJECT_DESCRIPTION") STORE AS BASICFILE (
 TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE NOLOGGING ) 
LOB ("PROJECT_DESIGN") STORE AS BASICFILE (
 TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE NOLOGGING ) ;
