--
-- Type: TABLE; Owner: BIOMART; Name: TEMP$$FOR_TEST
--
 CREATE TABLE "BIOMART"."TEMP$$FOR_TEST" 
  (	"BIO_MARKER_ID" NUMBER(18,0), 
"ASSO_BIO_MARKER_ID" NUMBER(18,0), 
"CORREL_TYPE" VARCHAR2(15 BYTE), 
"MV_ID" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
