--
-- Type: TABLE; Owner: BIOMART; Name: TESTS
--
 CREATE TABLE "BIOMART"."TESTS" 
  (	"NAME" VARCHAR2(100 BYTE), 
"PLATFORM" VARCHAR2(100 BYTE), 
"ID" NUMBER, 
"TEST" VARCHAR2(500 BYTE), 
"PROBESET" VARCHAR2(100 BYTE), 
"ESTIMATE" NUMBER(22,10), 
"FOLDCHANGE" NUMBER(22,10), 
"RAWPVALUE" NUMBER(22,10), 
"ADJUSTEDPVALUE" NUMBER(22,10), 
"MAXLSMEAN" NUMBER(22,10), 
"CONTRASTNAME" VARCHAR2(1000 BYTE), 
"VARIABLENAME" VARCHAR2(1000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

--
-- Type: INDEX; Owner: BIOMART; Name: IDX_TESTS
--
CREATE INDEX "BIOMART"."IDX_TESTS" ON "BIOMART"."TESTS" ("PLATFORM", "TEST")
TABLESPACE "USERS" ;

