--
-- Type: TABLE; Owner: BIOMART; Name: TMP_ANNOTATION2
--
 CREATE TABLE "BIOMART"."TMP_ANNOTATION2" 
  (	"PLATFORM" VARCHAR2(100 BYTE), 
"SPECIES" VARCHAR2(100 BYTE), 
"PROBE_ID" VARCHAR2(100 BYTE), 
"GENE_ID" VARCHAR2(20 BYTE), 
"GENE_SYMBOL" VARCHAR2(200 BYTE), 
"GENE_DESCR" VARCHAR2(1000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

