--
-- Type: TABLE; Owner: BIOMART; Name: TMP_ANALYSIS_DATA_TEA_RANK
--
 CREATE TABLE "BIOMART"."TMP_ANALYSIS_DATA_TEA_RANK" 
  (	"ANALYSIS_DATA_ID" NUMBER NOT NULL ENABLE, 
"ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"RANK1" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
--
-- Type: INDEX; Owner: BIOMART; Name: TMP_A_D_TEA_R_INDEX1
--
CREATE INDEX "BIOMART"."TMP_A_D_TEA_R_INDEX1" ON "BIOMART"."TMP_ANALYSIS_DATA_TEA_RANK" ("ANALYSIS_DATA_ID")
TABLESPACE "USERS" ;
