--
-- Type: TABLE; Owner: BIOMART; Name: TMP_ANALYSIS_DATA_TEA_RANK2
--
 CREATE TABLE "BIOMART"."TMP_ANALYSIS_DATA_TEA_RANK2" 
  (	"ANALYSIS_DATA_ID" NUMBER NOT NULL ENABLE, 
"ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"RANK1" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

