--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: CONCEPT_COUNTS_BKP
--
 CREATE TABLE "I2B2DEMODATA"."CONCEPT_COUNTS_BKP" 
  (	"CONCEPT_PATH" VARCHAR2(900 BYTE), 
"PARENT_CONCEPT_PATH" VARCHAR2(900 BYTE), 
"PATIENT_COUNT" NUMBER(38,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

