--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: ENCOUNTER_MAPPING
--
 CREATE TABLE "I2B2DEMODATA"."ENCOUNTER_MAPPING" 
  (	"ENCOUNTER_IDE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"ENCOUNTER_IDE_SOURCE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"ENCOUNTER_NUM" NUMBER(38,0) NOT NULL ENABLE, 
"PATIENT_IDE" VARCHAR2(200 BYTE), 
"PATIENT_IDE_SOURCE" VARCHAR2(50 BYTE), 
"ENCOUNTER_IDE_STATUS" VARCHAR2(50 BYTE), 
"UPDATE_DATE" DATE, 
"UPLOAD_DATE" DATE, 
"DOWNLOAD_DATE" DATE, 
"IMPORT_DATE" DATE, 
"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
"UPLOAD_ID" NUMBER(38,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

