--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: TOAD_PLAN_TABLE
--
 CREATE TABLE "I2B2DEMODATA"."TOAD_PLAN_TABLE" 
  (	"STATEMENT_ID" VARCHAR2(30 BYTE), 
"PLAN_ID" NUMBER, 
"TIMESTAMP" DATE, 
"REMARKS" VARCHAR2(4000 BYTE), 
"OPERATION" VARCHAR2(30 BYTE), 
"OPTIONS" VARCHAR2(255 BYTE), 
"OBJECT_NODE" VARCHAR2(128 BYTE), 
"OBJECT_OWNER" VARCHAR2(30 BYTE), 
"OBJECT_NAME" VARCHAR2(30 BYTE), 
"OBJECT_ALIAS" VARCHAR2(65 BYTE), 
"OBJECT_INSTANCE" NUMBER(*,0), 
"OBJECT_TYPE" VARCHAR2(30 BYTE), 
"OPTIMIZER" VARCHAR2(255 BYTE), 
"SEARCH_COLUMNS" NUMBER, 
"ID" NUMBER(*,0), 
"PARENT_ID" NUMBER(*,0), 
"DEPTH" NUMBER(*,0), 
"POSITION" NUMBER(*,0), 
"COST" NUMBER(*,0), 
"CARDINALITY" NUMBER(*,0), 
"BYTES" NUMBER(*,0), 
"OTHER_TAG" VARCHAR2(255 BYTE), 
"PARTITION_START" VARCHAR2(255 BYTE), 
"PARTITION_STOP" VARCHAR2(255 BYTE), 
"PARTITION_ID" NUMBER(*,0), 
"OTHER" LONG, 
"DISTRIBUTION" VARCHAR2(30 BYTE), 
"CPU_COST" NUMBER(*,0), 
"IO_COST" NUMBER(*,0), 
"TEMP_SPACE" NUMBER(*,0), 
"ACCESS_PREDICATES" VARCHAR2(4000 BYTE), 
"FILTER_PREDICATES" VARCHAR2(4000 BYTE), 
"PROJECTION" VARCHAR2(4000 BYTE), 
"TIME" NUMBER(*,0), 
"QBLOCK_NAME" VARCHAR2(30 BYTE), 
"OTHER_XML" CLOB
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" 
LOB ("OTHER_XML") STORE AS BASICFILE (
 TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE NOLOGGING ) ;

