--
-- Type: USER; Name: BIOMART
--
CREATE USER "BIOMART" IDENTIFIED BY VALUES 'S:7D433D387C0BB5E75B4A0EA69DB15DC0E7ED9A2321F5DF9C082CB10133D4;EE8EC2CF8301F8AE'
   DEFAULT TABLESPACE "USERS"
   TEMPORARY TABLESPACE "TEMP";

--
-- Type: TABLESPACE_QUOTA; Name: BIOMART
--
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "BIOMART" QUOTA UNLIMITED ON "USERS"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''USERS'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
 
--
-- Type: ROLE_GRANT; Name: BIOMART
--
GRANT "CONNECT" TO "BIOMART";

GRANT "DBA" TO "BIOMART";

GRANT "EXECUTE_CATALOG_ROLE" TO "BIOMART";

--
-- Type: SYSTEM_GRANT; Name: BIOMART
--
GRANT FLASHBACK ARCHIVE ADMINISTER TO "BIOMART";

GRANT ALTER DATABASE LINK TO "BIOMART";

GRANT ALTER PUBLIC DATABASE LINK TO "BIOMART";

GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "BIOMART";

GRANT UPDATE ANY CUBE DIMENSION TO "BIOMART";

GRANT UPDATE ANY CUBE BUILD PROCESS TO "BIOMART";

GRANT DROP ANY CUBE BUILD PROCESS TO "BIOMART";

GRANT CREATE ANY CUBE BUILD PROCESS TO "BIOMART";

GRANT CREATE CUBE BUILD PROCESS TO "BIOMART";

GRANT INSERT ANY MEASURE FOLDER TO "BIOMART";

GRANT DROP ANY MEASURE FOLDER TO "BIOMART";

GRANT DELETE ANY MEASURE FOLDER TO "BIOMART";

GRANT CREATE ANY MEASURE FOLDER TO "BIOMART";

GRANT CREATE MEASURE FOLDER TO "BIOMART";

GRANT UPDATE ANY CUBE TO "BIOMART";

GRANT SELECT ANY CUBE TO "BIOMART";

GRANT DROP ANY CUBE TO "BIOMART";

GRANT CREATE ANY CUBE TO "BIOMART";

GRANT ALTER ANY CUBE TO "BIOMART";

GRANT CREATE CUBE TO "BIOMART";

GRANT SELECT ANY CUBE DIMENSION TO "BIOMART";

GRANT INSERT ANY CUBE DIMENSION TO "BIOMART";

GRANT DROP ANY CUBE DIMENSION TO "BIOMART";

GRANT DELETE ANY CUBE DIMENSION TO "BIOMART";

GRANT CREATE ANY CUBE DIMENSION TO "BIOMART";

GRANT ALTER ANY CUBE DIMENSION TO "BIOMART";

GRANT CREATE CUBE DIMENSION TO "BIOMART";

GRANT COMMENT ANY MINING MODEL TO "BIOMART";

GRANT ALTER ANY MINING MODEL TO "BIOMART";

GRANT SELECT ANY MINING MODEL TO "BIOMART";

GRANT DROP ANY MINING MODEL TO "BIOMART";

GRANT CREATE ANY MINING MODEL TO "BIOMART";

GRANT CREATE MINING MODEL TO "BIOMART";

GRANT EXECUTE ASSEMBLY TO "BIOMART";

GRANT EXECUTE ANY ASSEMBLY TO "BIOMART";

GRANT DROP ANY ASSEMBLY TO "BIOMART";

GRANT ALTER ANY ASSEMBLY TO "BIOMART";

GRANT CREATE ANY ASSEMBLY TO "BIOMART";

GRANT CREATE ASSEMBLY TO "BIOMART";

GRANT ALTER ANY EDITION TO "BIOMART";

GRANT DROP ANY EDITION TO "BIOMART";

GRANT CREATE ANY EDITION TO "BIOMART";

GRANT CREATE EXTERNAL JOB TO "BIOMART";

GRANT CHANGE NOTIFICATION TO "BIOMART";

GRANT EXEMPT IDENTITY POLICY TO "BIOMART";

GRANT CREATE ANY SQL PROFILE TO "BIOMART";

GRANT ADMINISTER ANY SQL TUNING SET TO "BIOMART";

GRANT ADMINISTER SQL TUNING SET TO "BIOMART";

GRANT ALTER ANY SQL PROFILE TO "BIOMART";

GRANT DROP ANY SQL PROFILE TO "BIOMART";

GRANT SELECT ANY TRANSACTION TO "BIOMART";

GRANT MANAGE SCHEDULER TO "BIOMART";

GRANT EXECUTE ANY CLASS TO "BIOMART";

GRANT EXECUTE ANY PROGRAM TO "BIOMART";

GRANT CREATE ANY JOB TO "BIOMART";

GRANT CREATE JOB TO "BIOMART";

GRANT ADVISOR TO "BIOMART";

GRANT ANALYZE ANY DICTIONARY TO "BIOMART";

GRANT IMPORT FULL DATABASE TO "BIOMART";

GRANT EXPORT FULL DATABASE TO "BIOMART";

GRANT GRANT ANY OBJECT PRIVILEGE TO "BIOMART";

GRANT FLASHBACK ANY TABLE TO "BIOMART";

GRANT DEBUG ANY PROCEDURE TO "BIOMART";

GRANT DEBUG CONNECT SESSION TO "BIOMART";

GRANT SELECT ANY DICTIONARY TO "BIOMART";

GRANT RESUMABLE TO "BIOMART";

GRANT EXEMPT ACCESS POLICY TO "BIOMART";

GRANT ON COMMIT REFRESH TO "BIOMART";

GRANT MERGE ANY VIEW TO "BIOMART";

GRANT ADMINISTER DATABASE TRIGGER TO "BIOMART";

GRANT DROP ANY OUTLINE TO "BIOMART";

GRANT ALTER ANY OUTLINE TO "BIOMART";

GRANT CREATE ANY OUTLINE TO "BIOMART";

GRANT DROP ANY CONTEXT TO "BIOMART";

GRANT CREATE ANY CONTEXT TO "BIOMART";

GRANT DROP ANY DIMENSION TO "BIOMART";

GRANT ALTER ANY DIMENSION TO "BIOMART";

GRANT CREATE ANY DIMENSION TO "BIOMART";

GRANT CREATE DIMENSION TO "BIOMART";

GRANT UNDER ANY TABLE TO "BIOMART";

GRANT EXECUTE ANY INDEXTYPE TO "BIOMART";

GRANT GLOBAL QUERY REWRITE TO "BIOMART";

GRANT QUERY REWRITE TO "BIOMART";

GRANT UNDER ANY VIEW TO "BIOMART";

GRANT DROP ANY INDEXTYPE TO "BIOMART";

GRANT ALTER ANY INDEXTYPE TO "BIOMART";

GRANT CREATE ANY INDEXTYPE TO "BIOMART";

GRANT CREATE INDEXTYPE TO "BIOMART";

GRANT EXECUTE ANY OPERATOR TO "BIOMART";

GRANT DROP ANY OPERATOR TO "BIOMART";

GRANT ALTER ANY OPERATOR TO "BIOMART";

GRANT CREATE ANY OPERATOR TO "BIOMART";

GRANT CREATE OPERATOR TO "BIOMART";

GRANT EXECUTE ANY LIBRARY TO "BIOMART";

GRANT DROP ANY LIBRARY TO "BIOMART";

GRANT ALTER ANY LIBRARY TO "BIOMART";

GRANT CREATE ANY LIBRARY TO "BIOMART";

GRANT CREATE LIBRARY TO "BIOMART";

GRANT UNDER ANY TYPE TO "BIOMART";

GRANT EXECUTE ANY TYPE TO "BIOMART";

GRANT DROP ANY TYPE TO "BIOMART";

GRANT ALTER ANY TYPE TO "BIOMART";

GRANT CREATE ANY TYPE TO "BIOMART";

GRANT CREATE TYPE TO "BIOMART";

GRANT DROP ANY DIRECTORY TO "BIOMART";

GRANT CREATE ANY DIRECTORY TO "BIOMART";

GRANT DROP ANY MATERIALIZED VIEW TO "BIOMART";

GRANT ALTER ANY MATERIALIZED VIEW TO "BIOMART";

GRANT CREATE ANY MATERIALIZED VIEW TO "BIOMART";

GRANT CREATE MATERIALIZED VIEW TO "BIOMART";

GRANT GRANT ANY PRIVILEGE TO "BIOMART";

GRANT ANALYZE ANY TO "BIOMART";

GRANT ALTER RESOURCE COST TO "BIOMART";

GRANT DROP PROFILE TO "BIOMART";

GRANT ALTER PROFILE TO "BIOMART";

GRANT CREATE PROFILE TO "BIOMART";

GRANT DROP ANY TRIGGER TO "BIOMART";

GRANT ALTER ANY TRIGGER TO "BIOMART";

GRANT CREATE ANY TRIGGER TO "BIOMART";

GRANT CREATE TRIGGER TO "BIOMART";

GRANT EXECUTE ANY PROCEDURE TO "BIOMART";

GRANT DROP ANY PROCEDURE TO "BIOMART";

GRANT ALTER ANY PROCEDURE TO "BIOMART";

GRANT CREATE ANY PROCEDURE TO "BIOMART";

GRANT CREATE PROCEDURE TO "BIOMART";

GRANT FORCE ANY TRANSACTION TO "BIOMART";

GRANT FORCE TRANSACTION TO "BIOMART";

GRANT ALTER DATABASE TO "BIOMART";

GRANT AUDIT ANY TO "BIOMART";

GRANT ALTER ANY ROLE TO "BIOMART";

GRANT GRANT ANY ROLE TO "BIOMART";

GRANT DROP ANY ROLE TO "BIOMART";

GRANT CREATE ROLE TO "BIOMART";

GRANT DROP PUBLIC DATABASE LINK TO "BIOMART";

GRANT CREATE PUBLIC DATABASE LINK TO "BIOMART";

GRANT CREATE DATABASE LINK TO "BIOMART";

GRANT SELECT ANY SEQUENCE TO "BIOMART";

GRANT DROP ANY SEQUENCE TO "BIOMART";

GRANT ALTER ANY SEQUENCE TO "BIOMART";

GRANT CREATE ANY SEQUENCE TO "BIOMART";

GRANT CREATE SEQUENCE TO "BIOMART";

GRANT DROP ANY VIEW TO "BIOMART";

GRANT CREATE ANY VIEW TO "BIOMART";

GRANT CREATE VIEW TO "BIOMART";

GRANT DROP PUBLIC SYNONYM TO "BIOMART";

GRANT CREATE PUBLIC SYNONYM TO "BIOMART";

GRANT DROP ANY SYNONYM TO "BIOMART";

GRANT CREATE ANY SYNONYM TO "BIOMART";

GRANT CREATE SYNONYM TO "BIOMART";

GRANT DROP ANY INDEX TO "BIOMART";

GRANT ALTER ANY INDEX TO "BIOMART";

GRANT CREATE ANY INDEX TO "BIOMART";

GRANT DROP ANY CLUSTER TO "BIOMART";

GRANT ALTER ANY CLUSTER TO "BIOMART";

GRANT CREATE ANY CLUSTER TO "BIOMART";

GRANT CREATE CLUSTER TO "BIOMART";

GRANT DELETE ANY TABLE TO "BIOMART";

GRANT UPDATE ANY TABLE TO "BIOMART";

GRANT INSERT ANY TABLE TO "BIOMART";

GRANT SELECT ANY TABLE TO "BIOMART";

GRANT COMMENT ANY TABLE TO "BIOMART";

GRANT LOCK ANY TABLE TO "BIOMART";

GRANT DROP ANY TABLE TO "BIOMART";

GRANT BACKUP ANY TABLE TO "BIOMART";

GRANT ALTER ANY TABLE TO "BIOMART";

GRANT CREATE ANY TABLE TO "BIOMART";

GRANT CREATE TABLE TO "BIOMART";

GRANT DROP ROLLBACK SEGMENT TO "BIOMART";

GRANT ALTER ROLLBACK SEGMENT TO "BIOMART";

GRANT CREATE ROLLBACK SEGMENT TO "BIOMART";

GRANT DROP USER TO "BIOMART";

GRANT ALTER USER TO "BIOMART";

GRANT BECOME USER TO "BIOMART";

GRANT CREATE USER TO "BIOMART";

GRANT UNLIMITED TABLESPACE TO "BIOMART";

GRANT DROP TABLESPACE TO "BIOMART";

GRANT MANAGE TABLESPACE TO "BIOMART";

GRANT ALTER TABLESPACE TO "BIOMART";

GRANT CREATE TABLESPACE TO "BIOMART";

GRANT RESTRICTED SESSION TO "BIOMART";

GRANT ALTER SESSION TO "BIOMART";

GRANT CREATE SESSION TO "BIOMART";

GRANT AUDIT SYSTEM TO "BIOMART";

GRANT ALTER SYSTEM TO "BIOMART";

