--
-- Type: USER; Name: DEAPP
--
CREATE USER "DEAPP" IDENTIFIED BY VALUES 'S:C86DA9143E08C1C6158F2029110117927F7E6A45810E2ACBC9B171A1AFC2;9F7EF5372B0017FD'
   DEFAULT TABLESPACE "USERS"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: ROLE_GRANT; Name: DEAPP
--
GRANT "CONNECT" TO "DEAPP";
GRANT "DBA" TO "DEAPP";
--
-- Type: SYSTEM_GRANT; Name: DEAPP
--
GRANT UNLIMITED TABLESPACE TO "DEAPP";
--
-- Type: TABLESPACE_QUOTA; Name: DEAPP
--
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "DEAPP" QUOTA UNLIMITED ON "USERS"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''USERS'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
