--
-- Type: USER; Name: SEARCHAPP
--
CREATE USER "SEARCHAPP" IDENTIFIED BY VALUES 'S:6C06CFF80A220D5001747120FDEB73D1D9D80CCC23D6F59E284C881B1E76;ABAF57E22E1ABA89'
   DEFAULT TABLESPACE "USERS"
   TEMPORARY TABLESPACE "TEMP";

--
-- Type: SYSTEM_GRANT; Name: SEARCHAPP
--
GRANT FLASHBACK ARCHIVE ADMINISTER TO "SEARCHAPP";

GRANT ALTER DATABASE LINK TO "SEARCHAPP";

GRANT ALTER PUBLIC DATABASE LINK TO "SEARCHAPP";

GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "SEARCHAPP";

GRANT UPDATE ANY CUBE DIMENSION TO "SEARCHAPP";

GRANT UPDATE ANY CUBE BUILD PROCESS TO "SEARCHAPP";

GRANT DROP ANY CUBE BUILD PROCESS TO "SEARCHAPP";

GRANT CREATE ANY CUBE BUILD PROCESS TO "SEARCHAPP";

GRANT CREATE CUBE BUILD PROCESS TO "SEARCHAPP";

GRANT INSERT ANY MEASURE FOLDER TO "SEARCHAPP";

GRANT DROP ANY MEASURE FOLDER TO "SEARCHAPP";

GRANT DELETE ANY MEASURE FOLDER TO "SEARCHAPP";

GRANT CREATE ANY MEASURE FOLDER TO "SEARCHAPP";

GRANT CREATE MEASURE FOLDER TO "SEARCHAPP";

GRANT UPDATE ANY CUBE TO "SEARCHAPP";

GRANT SELECT ANY CUBE TO "SEARCHAPP";

GRANT DROP ANY CUBE TO "SEARCHAPP";

GRANT CREATE ANY CUBE TO "SEARCHAPP";

GRANT ALTER ANY CUBE TO "SEARCHAPP";

GRANT CREATE CUBE TO "SEARCHAPP";

GRANT SELECT ANY CUBE DIMENSION TO "SEARCHAPP";

GRANT INSERT ANY CUBE DIMENSION TO "SEARCHAPP";

GRANT DROP ANY CUBE DIMENSION TO "SEARCHAPP";

GRANT DELETE ANY CUBE DIMENSION TO "SEARCHAPP";

GRANT CREATE ANY CUBE DIMENSION TO "SEARCHAPP";

GRANT ALTER ANY CUBE DIMENSION TO "SEARCHAPP";

GRANT CREATE CUBE DIMENSION TO "SEARCHAPP";

GRANT COMMENT ANY MINING MODEL TO "SEARCHAPP";

GRANT ALTER ANY MINING MODEL TO "SEARCHAPP";

GRANT SELECT ANY MINING MODEL TO "SEARCHAPP";

GRANT DROP ANY MINING MODEL TO "SEARCHAPP";

GRANT CREATE ANY MINING MODEL TO "SEARCHAPP";

GRANT CREATE MINING MODEL TO "SEARCHAPP";

GRANT EXECUTE ASSEMBLY TO "SEARCHAPP";

GRANT EXECUTE ANY ASSEMBLY TO "SEARCHAPP";

GRANT DROP ANY ASSEMBLY TO "SEARCHAPP";

GRANT ALTER ANY ASSEMBLY TO "SEARCHAPP";

GRANT CREATE ANY ASSEMBLY TO "SEARCHAPP";

GRANT CREATE ASSEMBLY TO "SEARCHAPP";

GRANT ALTER ANY EDITION TO "SEARCHAPP";

GRANT DROP ANY EDITION TO "SEARCHAPP";

GRANT CREATE ANY EDITION TO "SEARCHAPP";

GRANT CREATE EXTERNAL JOB TO "SEARCHAPP";

GRANT CHANGE NOTIFICATION TO "SEARCHAPP";

GRANT EXEMPT IDENTITY POLICY TO "SEARCHAPP";

GRANT CREATE ANY SQL PROFILE TO "SEARCHAPP";

GRANT ADMINISTER ANY SQL TUNING SET TO "SEARCHAPP";

GRANT ADMINISTER SQL TUNING SET TO "SEARCHAPP";

GRANT ALTER ANY SQL PROFILE TO "SEARCHAPP";

GRANT DROP ANY SQL PROFILE TO "SEARCHAPP";

GRANT SELECT ANY TRANSACTION TO "SEARCHAPP";

GRANT MANAGE SCHEDULER TO "SEARCHAPP";

GRANT EXECUTE ANY CLASS TO "SEARCHAPP";

GRANT EXECUTE ANY PROGRAM TO "SEARCHAPP";

GRANT CREATE ANY JOB TO "SEARCHAPP";

GRANT CREATE JOB TO "SEARCHAPP";

GRANT ADVISOR TO "SEARCHAPP";

GRANT ANALYZE ANY DICTIONARY TO "SEARCHAPP";

GRANT IMPORT FULL DATABASE TO "SEARCHAPP";

GRANT EXPORT FULL DATABASE TO "SEARCHAPP";

GRANT GRANT ANY OBJECT PRIVILEGE TO "SEARCHAPP";

GRANT FLASHBACK ANY TABLE TO "SEARCHAPP";

GRANT DEBUG ANY PROCEDURE TO "SEARCHAPP";

GRANT DEBUG CONNECT SESSION TO "SEARCHAPP";

GRANT SELECT ANY DICTIONARY TO "SEARCHAPP";

GRANT RESUMABLE TO "SEARCHAPP";

GRANT EXEMPT ACCESS POLICY TO "SEARCHAPP";

GRANT ON COMMIT REFRESH TO "SEARCHAPP";

GRANT MERGE ANY VIEW TO "SEARCHAPP";

GRANT ADMINISTER DATABASE TRIGGER TO "SEARCHAPP";

GRANT DROP ANY OUTLINE TO "SEARCHAPP";

GRANT ALTER ANY OUTLINE TO "SEARCHAPP";

GRANT CREATE ANY OUTLINE TO "SEARCHAPP";

GRANT DROP ANY CONTEXT TO "SEARCHAPP";

GRANT CREATE ANY CONTEXT TO "SEARCHAPP";

GRANT DROP ANY DIMENSION TO "SEARCHAPP";

GRANT ALTER ANY DIMENSION TO "SEARCHAPP";

GRANT CREATE ANY DIMENSION TO "SEARCHAPP";

GRANT CREATE DIMENSION TO "SEARCHAPP";

GRANT UNDER ANY TABLE TO "SEARCHAPP";

GRANT EXECUTE ANY INDEXTYPE TO "SEARCHAPP";

GRANT GLOBAL QUERY REWRITE TO "SEARCHAPP";

GRANT QUERY REWRITE TO "SEARCHAPP";

GRANT UNDER ANY VIEW TO "SEARCHAPP";

GRANT DROP ANY INDEXTYPE TO "SEARCHAPP";

GRANT ALTER ANY INDEXTYPE TO "SEARCHAPP";

GRANT CREATE ANY INDEXTYPE TO "SEARCHAPP";

GRANT CREATE INDEXTYPE TO "SEARCHAPP";

GRANT EXECUTE ANY OPERATOR TO "SEARCHAPP";

GRANT DROP ANY OPERATOR TO "SEARCHAPP";

GRANT ALTER ANY OPERATOR TO "SEARCHAPP";

GRANT CREATE ANY OPERATOR TO "SEARCHAPP";

GRANT CREATE OPERATOR TO "SEARCHAPP";

GRANT EXECUTE ANY LIBRARY TO "SEARCHAPP";

GRANT DROP ANY LIBRARY TO "SEARCHAPP";

GRANT ALTER ANY LIBRARY TO "SEARCHAPP";

GRANT CREATE ANY LIBRARY TO "SEARCHAPP";

GRANT CREATE LIBRARY TO "SEARCHAPP";

GRANT UNDER ANY TYPE TO "SEARCHAPP";

GRANT EXECUTE ANY TYPE TO "SEARCHAPP";

GRANT DROP ANY TYPE TO "SEARCHAPP";

GRANT ALTER ANY TYPE TO "SEARCHAPP";

GRANT CREATE ANY TYPE TO "SEARCHAPP";

GRANT CREATE TYPE TO "SEARCHAPP";

GRANT DROP ANY DIRECTORY TO "SEARCHAPP";

GRANT CREATE ANY DIRECTORY TO "SEARCHAPP";

GRANT DROP ANY MATERIALIZED VIEW TO "SEARCHAPP";

GRANT ALTER ANY MATERIALIZED VIEW TO "SEARCHAPP";

GRANT CREATE ANY MATERIALIZED VIEW TO "SEARCHAPP";

GRANT CREATE MATERIALIZED VIEW TO "SEARCHAPP";

GRANT GRANT ANY PRIVILEGE TO "SEARCHAPP";

GRANT ANALYZE ANY TO "SEARCHAPP";

GRANT ALTER RESOURCE COST TO "SEARCHAPP";

GRANT DROP PROFILE TO "SEARCHAPP";

GRANT ALTER PROFILE TO "SEARCHAPP";

GRANT CREATE PROFILE TO "SEARCHAPP";

GRANT DROP ANY TRIGGER TO "SEARCHAPP";

GRANT ALTER ANY TRIGGER TO "SEARCHAPP";

GRANT CREATE ANY TRIGGER TO "SEARCHAPP";

GRANT CREATE TRIGGER TO "SEARCHAPP";

GRANT EXECUTE ANY PROCEDURE TO "SEARCHAPP";

GRANT DROP ANY PROCEDURE TO "SEARCHAPP";

GRANT ALTER ANY PROCEDURE TO "SEARCHAPP";

GRANT CREATE ANY PROCEDURE TO "SEARCHAPP";

GRANT CREATE PROCEDURE TO "SEARCHAPP";

GRANT FORCE ANY TRANSACTION TO "SEARCHAPP";

GRANT FORCE TRANSACTION TO "SEARCHAPP";

GRANT ALTER DATABASE TO "SEARCHAPP";

GRANT AUDIT ANY TO "SEARCHAPP";

GRANT ALTER ANY ROLE TO "SEARCHAPP";

GRANT GRANT ANY ROLE TO "SEARCHAPP";

GRANT DROP ANY ROLE TO "SEARCHAPP";

GRANT CREATE ROLE TO "SEARCHAPP";

GRANT DROP PUBLIC DATABASE LINK TO "SEARCHAPP";

GRANT CREATE PUBLIC DATABASE LINK TO "SEARCHAPP";

GRANT CREATE DATABASE LINK TO "SEARCHAPP";

GRANT SELECT ANY SEQUENCE TO "SEARCHAPP";

GRANT DROP ANY SEQUENCE TO "SEARCHAPP";

GRANT ALTER ANY SEQUENCE TO "SEARCHAPP";

GRANT CREATE ANY SEQUENCE TO "SEARCHAPP";

GRANT CREATE SEQUENCE TO "SEARCHAPP";

GRANT DROP ANY VIEW TO "SEARCHAPP";

GRANT CREATE ANY VIEW TO "SEARCHAPP";

GRANT CREATE VIEW TO "SEARCHAPP";

GRANT DROP PUBLIC SYNONYM TO "SEARCHAPP";

GRANT CREATE PUBLIC SYNONYM TO "SEARCHAPP";

GRANT DROP ANY SYNONYM TO "SEARCHAPP";

GRANT CREATE ANY SYNONYM TO "SEARCHAPP";

GRANT CREATE SYNONYM TO "SEARCHAPP";

GRANT DROP ANY INDEX TO "SEARCHAPP";

GRANT ALTER ANY INDEX TO "SEARCHAPP";

GRANT CREATE ANY INDEX TO "SEARCHAPP";

GRANT DROP ANY CLUSTER TO "SEARCHAPP";

GRANT ALTER ANY CLUSTER TO "SEARCHAPP";

GRANT CREATE ANY CLUSTER TO "SEARCHAPP";

GRANT CREATE CLUSTER TO "SEARCHAPP";

GRANT DELETE ANY TABLE TO "SEARCHAPP";

GRANT UPDATE ANY TABLE TO "SEARCHAPP";

GRANT INSERT ANY TABLE TO "SEARCHAPP";

GRANT SELECT ANY TABLE TO "SEARCHAPP";

GRANT COMMENT ANY TABLE TO "SEARCHAPP";

GRANT LOCK ANY TABLE TO "SEARCHAPP";

GRANT DROP ANY TABLE TO "SEARCHAPP";

GRANT BACKUP ANY TABLE TO "SEARCHAPP";

GRANT ALTER ANY TABLE TO "SEARCHAPP";

GRANT CREATE ANY TABLE TO "SEARCHAPP";

GRANT CREATE TABLE TO "SEARCHAPP";

GRANT DROP ROLLBACK SEGMENT TO "SEARCHAPP";

GRANT ALTER ROLLBACK SEGMENT TO "SEARCHAPP";

GRANT CREATE ROLLBACK SEGMENT TO "SEARCHAPP";

GRANT DROP USER TO "SEARCHAPP";

GRANT ALTER USER TO "SEARCHAPP";

GRANT BECOME USER TO "SEARCHAPP";

GRANT CREATE USER TO "SEARCHAPP";

GRANT UNLIMITED TABLESPACE TO "SEARCHAPP";

GRANT DROP TABLESPACE TO "SEARCHAPP";

GRANT MANAGE TABLESPACE TO "SEARCHAPP";

GRANT ALTER TABLESPACE TO "SEARCHAPP";

GRANT CREATE TABLESPACE TO "SEARCHAPP";

GRANT RESTRICTED SESSION TO "SEARCHAPP";

GRANT ALTER SESSION TO "SEARCHAPP";

GRANT CREATE SESSION TO "SEARCHAPP";

GRANT AUDIT SYSTEM TO "SEARCHAPP";

GRANT ALTER SYSTEM TO "SEARCHAPP";

--
-- Type: ROLE_GRANT; Name: SEARCHAPP
--
GRANT "CONNECT" TO "SEARCHAPP";

GRANT "DBA" TO "SEARCHAPP";

--
-- Type: TABLESPACE_QUOTA; Name: SEARCHAPP
--
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "SEARCHAPP" QUOTA UNLIMITED ON "USERS"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''USERS'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
 
