--
-- Type: VIEW; Owner: BIOMART; Name: BIO_ASSAY_DATA_TEA_TOP50_MV
--
  CREATE OR REPLACE FORCE VIEW "BIOMART"."BIO_ASSAY_DATA_TEA_TOP50_MV" ("BIO_ASY_ANALYSIS_DATA_ID", "FOLD_CHANGE_RATIO", "RAW_PVALUE", "ADJUSTED_PVALUE", "R_VALUE", "RHO_VALUE", "BIO_ASSAY_ANALYSIS_ID", "ADJUSTED_P_VALUE_CODE", "FEATURE_GROUP_NAME", "BIO_EXPERIMENT_ID", "BIO_ASSAY_PLATFORM_ID", "ETL_ID", "PREFERRED_PVALUE", "CUT_VALUE", "RESULTS_VALUE", "NUMERIC_VALUE", "NUMERIC_VALUE_CODE", "TEA_NORMALIZED_PVALUE", "BIO_EXPERIMENT_TYPE", "BIO_ASSAY_FEATURE_GROUP_ID", "TEA_RANK") AS 
  SELECT "BIO_ASY_ANALYSIS_DATA_ID","FOLD_CHANGE_RATIO","RAW_PVALUE","ADJUSTED_PVALUE","R_VALUE","RHO_VALUE","BIO_ASSAY_ANALYSIS_ID","ADJUSTED_P_VALUE_CODE","FEATURE_GROUP_NAME","BIO_EXPERIMENT_ID","BIO_ASSAY_PLATFORM_ID","ETL_ID","PREFERRED_PVALUE","CUT_VALUE","RESULTS_VALUE","NUMERIC_VALUE","NUMERIC_VALUE_CODE","TEA_NORMALIZED_PVALUE","BIO_EXPERIMENT_TYPE","BIO_ASSAY_FEATURE_GROUP_ID","TEA_RANK"   
FROM bio_assay_analysis_data_tea
where tea_rank<=50
 ;
