--
-- Type: TABLE; Owner: TM_CZ; Name: CZ_DATA_PROFILE_COLUMN_SAMPLE
--
 CREATE TABLE "TM_CZ"."CZ_DATA_PROFILE_COLUMN_SAMPLE" 
  (	"TABLE_NAME" VARCHAR2(500 BYTE), 
"COLUMN_NAME" VARCHAR2(500 BYTE), 
"VALUE" VARCHAR2(4000 BYTE), 
"COUNT" NUMBER(19,0), 
"ETL_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

