--
-- Type: TABLE; Owner: TM_CZ; Name: CZ_XTRIAL_CTRL_VOCAB
--
 CREATE TABLE "TM_CZ"."CZ_XTRIAL_CTRL_VOCAB" 
  (	"CTRL_VOCAB_CODE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"CTRL_VOCAB_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"CTRL_VOCAB_CATEGORY" VARCHAR2(200 BYTE), 
"CTRL_VOCAB_ID" NUMBER(18,0) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

--
-- Type: TRIGGER; Owner: TM_CZ; Name: TRG_XTRIAL_CTRL_VOCAB_ID
--
  CREATE OR REPLACE TRIGGER "TM_CZ"."TRG_XTRIAL_CTRL_VOCAB_ID" 
before insert on "CZ_XTRIAL_CTRL_VOCAB"    for each row 
begin     if inserting then       
if :NEW."CTRL_VOCAB_ID" is null then          
select SEQ_CZ.nextval into :NEW."CTRL_VOCAB_ID" from dual;       end if;       end if;   end;


/
ALTER TRIGGER "TM_CZ"."TRG_XTRIAL_CTRL_VOCAB_ID" ENABLE;
 
