--
-- Type: TABLE; Owner: TM_CZ; Name: I2B2_TAGS_BK
--
 CREATE TABLE "TM_CZ"."I2B2_TAGS_BK" 
  (	"TAG_ID" NUMBER(18,0) NOT NULL ENABLE, 
"PATH" VARCHAR2(400 BYTE), 
"TAG" VARCHAR2(400 BYTE), 
"TAG_TYPE" VARCHAR2(400 BYTE), 
"TAGS_IDX" NUMBER(22,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

