--
-- Type: TABLE; Owner: TM_CZ; Name: I2B2_TAGS_RELEASE
--
 CREATE TABLE "TM_CZ"."I2B2_TAGS_RELEASE" 
  (	"TAG_ID" NUMBER(18,0) NOT NULL ENABLE, 
"PATH" VARCHAR2(400 BYTE), 
"TAG" VARCHAR2(400 BYTE), 
"TAG_TYPE" VARCHAR2(400 BYTE), 
"TAGS_IDX" NUMBER(22,0), 
"RELEASE_STUDY" VARCHAR2(400 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;
