--
-- Type: TABLE; Owner: TM_CZ; Name: TMP_NOCOMPOUND_REMAP
--
 CREATE TABLE "TM_CZ"."TMP_NOCOMPOUND_REMAP" 
  (	"OLD_PID" NUMBER(38,0), 
"NEW_PID" NUMBER(38,0), 
"OLD_SOURCECD" VARCHAR2(50 BYTE), 
"NEW_SOURCECD" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

