--
-- Type: TABLE; Owner: TM_CZ; Name: TMP_TREE_NODES
--
 CREATE TABLE "TM_CZ"."TMP_TREE_NODES" 
  (	"LEAF_NODE" VARCHAR2(4000 BYTE), 
"NODE_NAME" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

