--
-- Type: TABLE; Owner: TM_CZ; Name: TMP_C0524T03_PATIENT_MAPPING
--
 CREATE TABLE "TM_CZ"."TMP_C0524T03_PATIENT_MAPPING" 
  (	"OLD_PATIENT_NUM" NUMBER(38,0), 
"NEW_PATIENT_NUM" NUMBER(38,0), 
"SOURCESYSTEM_CD" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "USERS" ;

